name: CI (TypeScript)

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22] # LTS + current
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck --if-present # tsc --noEmit

      - name: Lint
        run: npm run lint --if-present

      - name: Unit tests
        run: npm test --if-present -- --ci --reporters=default

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifacts (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-build-${{ matrix.node }}
          path: |
            dist
            build
          if-no-files-found: ignore
